# Servidor
server.port=${PORT:8080}

# Base de datos local (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/sigepro?useSSL=false&serverTimezone=America/Lima&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=SIGEPRO_SECRET_KEY_2026_TRANSANDINA_SA_PROYECTO_FINAL_UNIVERSITARIO
jwt.expiration=86400000

# Swagger / OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
